In [1]:
!pip freeze

appnope==0.1.3
argcomplete==1.10.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asgiref==3.5.0
asttokens==2.0.7
attrs==21.2.0
autopep8==1.5.7
backcall==0.2.0
beautifulsoup4==4.8.2
bleach==4.1.0
bs4==0.0.1
certifi==2021.5.30
cffi==1.15.1
chardet==3.0.4
charset-normalizer==2.0.4
cli-exit-tools==1.1.8
click==8.0.2
colorama==0.4.4
compressed-rtf==1.0.6
debugpy==1.6.2
decorator==5.1.1
defusedxml==0.7.1
Django==4.0.2
docutils==0.17.1
docx2txt==0.8
ebcdic==1.1.1
entrypoints==0.4
executing==0.9.1
extract-msg==0.28.7
fake-winreg==1.5.6
fastjsonschema==2.16.1
Flask==2.0.2
Flask-Cors==3.0.10
ghs==0.1.3
google==3.0.0
gpfetcher==0.8.6
gunicorn==20.1.0
halo==0.0.31
idna==3.2
IMAPClient==2.1.0
importlib-metadata==4.8.1
iniconfig==1.1.1
ipykernel==6.15.1
ipython==8.4.0
ipython-genutils==0.2.0
isodate==0.6.1
itsdangerous==2.0.1
jedi==0.18.1
Jinja2==3.0.3
joblib==1.1.0
jsonschema==4.9.1
jupyter-client==7.3.4
jupyter-core==4.11.1
jupyterlab-pygments==0.2.2
keyring==23.2.1
lib-platform==1.2.7
lib-regi

In [9]:
print("Hello")

import numpy as n
print(n.array([1,2,3,4,5,6,12,3,4]).reshape((3,3)))

Hello
[[ 1  2  3]
 [ 4  5  6]
 [12  3  4]]


In [11]:
from gpfetcher import scraper

user  = input("Enter github username: ")
scraper.scrape(user)

Enter github username: devgautam2000
Hello devgautam2000

66 repositories found.
NOTE: The private repositories will not be fetched.



100%|███████████████████████████████████████████| 66/66 [00:13<00:00,  4.86it/s]

Done! checkout your devgautam2000-projects.json file at the root of this directory

