In [52]:
from sklearn import svm,datasets as ds
from sklearn.metrics import accuracy_score as acs, confusion_matrix as cf
from sklearn.model_selection import train_test_split as tts
import numpy as np
import pandas as pd

x_d,y_d = ds.load_diabetes(return_X_y=True)

x = pd.DataFrame(x_d).iloc[:,1:].values
y = pd.DataFrame(y_d).iloc[:,0].values


In [53]:
x_tr,xt,y_tr,yt = tts(x,y,test_size=0.3,random_state=1)

In [59]:
typesOfKernel = [ 'linear', 'poly', 'rbf' ]

model = svm.SVC(kernel='rbf')

model.fit(x_tr,y_tr)
pred = model.predict(xt)

pred

array([128.,  72., 128.,  72., 275., 275., 275.,  53.,  53.,  72., 128.,
        91.,  53.,  72., 275., 275.,  85.,  72.,  91., 275., 275.,  72.,
        72.,  72.,  72., 275.,  72., 200.,  91., 275.,  85., 128.,  91.,
        72.,  72.,  91.,  72., 275., 128.,  91.,  85.,  85.,  53.,  53.,
        72., 248., 128., 200., 275., 248.,  72., 128.,  85.,  72., 275.,
        53.,  85.,  53.,  72.,  72.,  53., 275.,  91.,  72., 248.,  72.,
        72., 131.,  91.,  72., 128.,  72.,  72.,  53.,  91.,  87.,  53.,
        72., 275., 200.,  53.,  53., 200., 142.,  72.,  53.,  72.,  72.,
       275.,  84.,  91., 128.,  72.,  53.,  72., 200., 200.,  53.,  85.,
       128.,  72.,  72.,  72., 202., 275.,  91., 248., 275.,  72.,  72.,
       200., 248., 248.,  72., 275., 200.,  72.,  72.,  85.,  91.,  72.,
       310., 275.,  53.,  53., 142.,  72.,  53., 113.,  53.,  53., 128.,
        53.])

In [60]:
print(f"Acuuracy score: {acs(yt,pred)}")
print(f"confusion matrix: \n{cf(yt,pred)}")

Acuuracy score: 0.007518796992481203
confusion matrix: 
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
